# Generated by Django 4.0.3 on 2022-03-01 15:24

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', students.models.LowerCaseCharField(db_index=True, max_length=30)),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', students.models.LowerCaseCharField(db_index=True, max_length=20)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.college')),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='college',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='college_name_should_be_unique'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(check=models.Q(('gpa__gte', 0), ('gpa__lte', 10)), name='student_gpa_should_be_between_0_and_10'),
        ),
    ]
